### ISSUE TITLE
configuration options

### ISSUE THREAD

**Issue by jnankin** [redis-store/redis-rack#1]
can you add something to the readme about how to configure this?  i want to change the session store to point to a redis box on another machine.  how do i do that?

**Comment by kuraga** [comment]
@redis-store, ping

**Comment by kuraga** [comment]
@redis-store, @jodosha, @radar 
ping!

**Comment by kuraga** [comment]
@redis-store, @jodosha, @radar 
would you like to merge my PR about this issue?

**Comment by radar** [comment]
3 pings?!

**Comment by radar** [comment]
@kuraga; which PR?

**Comment by kuraga** [comment]
Sorry about three pings but I added more recipients....

I could make a PR for:
```ruby
redis_instance = Redis.new(options)
use Rack::Session::Redis, backend: redis_instance
```
Or you?

**Comment by radar** [comment]
Yes. Can you please create this PR to add more documentation?
