### ISSUE TITLE
No configuration instructions

### ISSUE THREAD

**Issue by CullenShane** [redis-store/redis-rack#15]
There are no instructions for how to configure the connection parameters in the Readme.

They are also not in the parent project, but the parent project Readme says that they should be in the child projects.

**Comment by tubbo** [comment]
The ["Usage" section of redis-rack-cache](https://github.com/redis-store/redis-rack-cache#usage) includes some information on setting up the redis store in a rack-cache configuration scenario. Are you talking about something more low-level?

**Comment by CullenShane** [comment]
There are instructions there, but they don't apply to this gem.  I ended up reading the code for my Sinatra application and guessing what the right hash values were.  They aren't the same keys as Rack::Cache, or the Rack::Rails::Session.  I'll be happy to write a usage section, could you tell me what the other configuration keys are?

This is what I ended up using:
`
require 'rack'
require 'rack/session/redis'

use Rack::Session::Redis, redis_server: ENV['REDIS_URL']
`

**Comment by tubbo** [comment]
There are these default options from Rack::Session::Abstract::ID https://github.com/rack/rack/blob/1.6.4/lib/rack/session/abstract/id.rb#L195-L207

But I think those should be documented in the Rack project. As far as what we're adding to the session config hash, take a look at https://github.com/redis-store/redis-rack/blob/master/lib/rack/session/redis.rb#L17-L31

I would also gladly accept a pull request for a Usage section, or any new documentation for that matter, on this and all the other redis-store gems.
