### ISSUE TITLE
Passing a ConnectionPool as the pool parameter causes error

### ISSUE THREAD

**Issue by jeffblake** [redis-store/redis-rack#16]
Error caused whenever the session is accessed:

ArgumentError - wrong number of arguments (given 3, expected 2):
  redis (3.2.2) lib/redis.rb:750:in `setnx'
   () Users/jblake/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/redis-rack-83a7b7b895bb/lib/rack/session/redis.rb:39:in`block (2 levels) in generate_unique_sid'

This is what I setup:

```
redis_conn = proc {
  Redis.new(url: ENV.fetch('REDIS_URL'))
}

$redis = ConnectionPool.new(size: ENV.fetch('REDIS_POOL', 5), &redis_conn)
uri = URI.parse(ENV.fetch('REDIS_URL'))

Rails.application.config.session_store :redis_store, {
  servers: {
    host: uri.host,
    port: uri.port || nil,
    password: uri.password,
    namespace: 'sessions'
  },
  domain: :all,
  tld_length: 2,
  namespace: :session,
  pool: $redis
}

```

Looking at the source code, if I were to pass a pool_size instead, you use the Redis Factory to create the redis instance, whereas I'm using `Redis.new`. Maybe this is an incompatibility, I don't know, all I know is that I want to share the same ConnectionPool for my session store and sidekiq client (I think this is a good idea?)

```
Sidekiq.configure_client do |config|
  config.redis = $redis
end
```

**Comment by tubbo** [comment]
@dreyks the problem looks like it's on https://github.com/redis-store/redis-rack/blob/master/lib/rack/session/redis.rb#L39, and on https://github.com/redis/redis-rb/blob/master/lib/redis.rb#L750-L754 it seems the `setnx` method only takes 2 arguments.

Does this work for you if you pass a `:pool_size`?

**Comment by jeffblake** [comment]
I'm still testing the actual connection counts, but yes if I set pool_size then it will boot up and work. Makes it hard to control the # of connections though, since if you multiply # of puma processes x pool_size(8) x # dynos...x 2 (for sidekiq) ... it can get out of control quick.

**Comment by jeffblake** [comment]
Hey,

I found this gem: https://github.com/librato/librato-rack-source_prefix

which takes care of this for us.

**Comment by tubbo** [comment]
@jeffblake I'd be interested to see a pull request that makes your use case a little easier, but since this issue is no longer a problem for you, I'm gonna close it. Feel free to continue hacking on this, though...but since it's still possible (though a little kludgey), I'm going to say it's no longer an actual bug but rather just a place we can/should improve the API.
