### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by byroot** [redis-store/redis-rack#17]
Hi,

I'm affected by #1 (no way to pass configuration options) but it's still not released.

Could you publish a new release?

Regards

**Comment by tubbo** [comment]
https://github.com/redis-store/redis-rack/issues/1#issuecomment-43249891 states that this functionality is currently available, but spawns a separate instance of the `Redis::Store` object which is slightly inefficient. The only change made in that PR is to be able to configure the actual `Redis::Store` object. The assertion that there is currently "no way to pass configuration options" is false.

That said, I'm happy to pre-release the next version of this gem so it's easier to test. I just wanted you to be aware that you can still configure `Redis::Rack` as documented within that ticket.

**Comment by connorshea** [comment]
@tubbo can we get a 2.0.0 final release?

**Comment by tubbo** [comment]
@connorshea Done. v2.0.0 is up on RubyGems, built from the 2.0.0 tag on this repo.

**Comment by connorshea** [comment]
@tubbo thanks :)
