### ISSUE TITLE
Gracefully handling loss of redis connection

### ISSUE THREAD

**Issue by rwc9u** [redis-store/redis-rack#25]
https://github.com/redis-store/redis-rack/blob/master/lib/rack/session/redis.rb#L76 

rescues for ```Errno::ECONNREFUSED``` 
however the redis gem raises:
```::Redis::CannotConnectError``` and if you catch this there is another location a NotMethodError is thrown on set_session. Would a pull request to add an option to raise or suppress errors similar to redis-activesupport gem be useful?

I've monkey-patched our application so if redis is not available the public facing application still renders but you cannot log in. If you think this is useful I can submit a pull request.

**Comment by tubbo** [comment]
It seems like if you just replaced that line with...

```ruby
rescue Errno::ECONNREFUSED, ::Redis::CannotConnectError
```

Then `Rack::Session::Redis#with_lock` would work as expected, warning you when the connection fails but not crashing out of your program. [Rescuing ECONNREFUSED and replacing it with CannotConnectError](https://github.com/redis/redis-rb/pull/463) was added to the Redis client, but it seems we never updated our own `rescue` here to account for the change.

**Comment by rwc9u** [comment]
That fixes the first issue and my additional issue may be an issue with our environment/version constraints. We're running an older version of the gem due to production environment constraints. That's exactly what I tried first and it does fix the first problem. I then ran into an issue where namespace matching in the redis-store gem fails because the session_id key is nil on set_session. I fixed by just monkey-patching to rescue StandardError.

The following is an example stacktrace of what I'm seeing with respect to a nil key and the use of a namespace.

```
NoMethodError: undefined method `match' for nil:NilClass
Did you mean?  catch
/usr/local/rvm/gems/ruby-2.3.3@investor/gems/redis-store-1.1.7/lib/redis/store/namespace.rb:82:in `interpolate'
/usr/local/rvm/gems/ruby-2.3.3@investor/gems/redis-store-1.1.7/lib/redis/store/namespace.rb:74:in `namespace'
/usr/local/rvm/gems/ruby-2.3.3@investor/gems/redis-store-1.1.7/lib/redis/store/namespace.rb:5:in `set'
/usr/local/rvm/gems/ruby-2.3.3@investor/gems/redis-rack-1.5.0/lib/rack/session/redis.rb:41:in `block in set_session'
```

**Comment by tubbo** [comment]
@rwc9u why is the `session_id` nil?
