### ISSUE TITLE
When will redis-rack with redis-store ~> 1.4.0 be released?

### ISSUE THREAD

**Issue by Prajna** [redis-store/redis-rack#31]
Hi,
Thank you for your great work.
redis-store is now 1.4.0, but redis-rack/redis-actionpack/redis-activesupport still requires 1.3.0, when will these gems be released?

Thanks.

**Comment by tubbo** [comment]
hey @Prajna, sorry for the delay...working on getting 1.4.0 compatibility rolled out for all redis-* gems today. will update this issue and close it when the newest redis-rack is released.

**Comment by tubbo** [comment]
@Prajna v2.0.3 has the ability to use redis-store 1.4

**Comment by Prajna** [comment]
hey @tubbo thank you so much
