### ISSUE TITLE
redis-rack trashing rbenv shims of other gems?

### ISSUE THREAD

**Issue by canoeberry** [redis-store/redis-rack#32]
I am reluctant to bring this up but I don't even know where to begin with this issue.

My terminology is wrong, too. I guess gems are invoked by shell scripts that fire up ruby, load gems, and then invoke the gem in question. Those ruby scripts are getting trashed, being over-written with redis-rack.

So far it's happened to the rake command and the appraisal command.

```$ cat appraisal 
#!/usr/bin/env ruby
#
# This file was generated by RubyGems.
#
# The application 'redis-rack' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

load Gem.activate_bin_path('redis-rack', 'appraisal', version)
```
Here is appraisal and the end of the shim says "redis-rack". This also happened to my rake command. It keeps happening when I switch ruby versions.

Sorry about the empty looking Issue. I pressed return before entering the description.

**Comment by tubbo** [comment]
@canoeberry i have no idea what this issue means, but i've never insulted anyone else's gem before in my life

**Comment by tubbo** [comment]
Interesting issue! It looks like we're configuring the gem to look in `bin/` for executables, but we don't actually ship executables as a part of this gem, so that _might_ be confusing the living shit out of RubyGems and forcing it to generate binstubs for redis-rack that it doesn't need to.

I'll remove that line from the gemspec and release a patch version to see if it fixes anything.

**Comment by canoeberry** [comment]
Hey - thanks for having a look.

When I was deploying to a remote server, I saw a warning message about binstubs and deprecated behavior that I thought might be relevant but still couldn't fathom why it would do what it's doing. The issue is happening on my laptop and not the remote server where I saw that error.

**Comment by canoeberry** [comment]
Is there some modification I can make to the gem to see if it stops this problem?
