### ISSUE TITLE
problem with parsing sessions array

### ISSUE THREAD

**Issue by sebastjan-hribar** [redis-store/redis-rack#35]
I'm using redis-rack with Hanami and Hanami model.

Currently I'm storing the entire user as `session[current_user] = user` which returns all the user data in the array of hashes as shown below. I've left some of the data out for brevity. The problem is, that I can't parse the data below due to the following:

The time is not formatted as string: `"session_start_time"=>2018-03-29 09:48:04 +0200` => I guess I can fix this when setting the time.
The comment sign: `"current_user"=>#1`
And the greater than and curly braces `>}`

What I've also noticed is that after I clear the session in the logout action like `session.clear` there are still references to that session as seen in the empty hashes below.

```
[ { 
"_csrf_token"=>"token", 
"LOCK"=>"Off", 
"session_start_time"=>2018-03-29 09:48:04 +0200, 
"__last_request_id"=>"fa7b2343a245e7d80455bd56dfe0b665", 
"__flash"=>{ 
"bb3eab2445e49b7d32b33552f3b7a1ef"=>{:success_notice=>"Login successful."}, 
"fa7b2343a245e7d80455bd56dfe0b665"=>{}
 }, 
"current_user"=>#1,
 :name=>"my_name",
 :surname=>"my_surname",
 :email=>"my_email@mail.com" }>}, 
{}, 
{ "__flash"=>{ "0ae1af60026095a75b99902b2bb3b755"=>{:success_notice=>"Logout successful."}, "37858ee72e55d2e307e53732209cc4df"=>{} }, 
"__last_request_id"=>"37858ee72e55d2e307e53732209cc4df", 
"_csrf_token"=>"token",
 "LOCK"=>"Off" },
 {}, 
{} ]
```

**Comment by tubbo** [comment]
@sebastjan-hribar First of all, sorry for getting back to you so late. :) The `Redis::Rack` gem doesn't handle any kind of marshalling, and I'm not sure how it will try to store a Hash to Redis if not marshalled prior to going in. I'm not sure if `Hanami::Model` provides this for you, either, but it might be worth checking out. Not sure how the Hash data ended up that way...[redis-rack is just setting whatever Hanami puts into the hash as the session](https://github.com/redis-store/redis-rack/blob/master/lib/rack/session/redis.rb#L48).

**Comment by tubbo** [comment]
hey @sebastjan-hribar did that answer your question? if so, I'm gonna close this issue...

**Comment by sebastjan-hribar** [comment]
I'm sorry for late reply. I see now about not being marshalled. I'll refactor my code to properly process data before it hits Redis. Meanwhile I've found an intermediate solution for parsing the data above.
