### ISSUE TITLE
Tests failed during Debian packaging

### ISSUE THREAD

**Issue by balasankarc** [redis-store/redis-rack#4]
Hi, I am packaging redis-rack for debian and whule running the tests, I am getting an error.
The full log is given here - http://pastebin.com/vRcnBFQr

Can you help me solve this?

**Comment by radar** [comment]
Hi @balasankarc. Is this still a problem? If so, which version of redis-store are you using?

**Comment by balasankarc** [comment]
@radar .. I am sorry.. It was a mistake from my side and I corrected it.. Had totally forgotten about this issue.. Sorry for the inconvenience caused.. Redis-rack is in Debian unstable now..

**Comment by radar** [comment]
No worries. Thanks for letting me know that this issue is now solved :)
