### ISSUE TITLE
Version 2.1.1 is missing. Can't install.

### ISSUE THREAD

**Issue by kntmrkm** [redis-store/redis-rack#54]
see
https://rubygems.org/gems/redis-rack

```
Fetching gem metadata from https://rubygems.org/......
Could not find redis-rack-2.1.1 in any of the sources
```

**Comment by gongo** [comment]
> this has been reverted and 2.1.1 was yanked. continuing to use 2.1.0 should be fine.
>
> https://github.com/redis-store/redis-rack/pull/51#issuecomment-579851539

**Comment by kntmrkm** [comment]
thanks @gongo
