### ISSUE TITLE
built in rake conflict

### ISSUE THREAD

**Issue by zevarito** [redis-store/redis-rack#57]
I got this message every time using rake on a project that already have bundled it, no question if it is illegal or not, I've read that Bundler put that there I believe? but is it need/worth?

```
The `rake` executable in the `rake` gem is being loaded, but it's also present in other gems (redis-rack).
If you meant to run the executable for another gem, make sure you use a project specific binstub (`bundle binstub <gem_name>`).
If you plan to use multiple conflicting executables, generate binstubs for them and disambiguate their names.
```

**Comment by tubbo** [comment]
hey can you try running `bundle update redis-rack`? I think you're using an older version which still had the `bin/` directory included as executables for the gem.

**Comment by zevarito** [comment]
I've tried but version stay the same:

`Bundler attempted to update redis-rack-cache but its version stayed the same
Bundle updated!`

**Comment by tubbo** [comment]
@zevarito no problem! I remember us fixing this issue a while back. Those crazy RubyGems defaults...
