### ISSUE TITLE
Incompatible with Redis Store 1.9.0

### ISSUE THREAD

**Issue by PikachuEXE** [redis-store/redis-rack#60]
The passed in options is a `ActionDispatch::Request::Session::Options` which does not have `#key?`
![image](https://user-images.githubusercontent.com/1018543/85352391-6a091e80-b538-11ea-9c17-5fb77f39c8ec.png)

**Comment by tubbo** [comment]
I'm working on a fix for this in redis-store/redis-store#337, it should land in `master` soon if you want to try it out.

**Comment by johnmichaelbradley** [comment]
Would this be something that you could justify a revision release for?

**Comment by PikachuEXE** [comment]
Already released
https://rubygems.org/gems/redis-rack/versions/2.1.3
https://github.com/redis-store/redis-rack/commit/5eed7565cf268a68801409e49364513419fa89c6
