### ISSUE TITLE
Got "undefined method `public_id' for String" when calling delete_session

### ISSUE THREAD

**Issue by johnny-miyake** [redis-store/redis-rack#62]
With redis-rack 2.1.3, I got this error.
```
     NoMethodError:
       undefined method `public_id' for "b2df46eb3fa3bdfc657fd814bc668114":String
       Did you mean?  public_send
     # /usr/local/bundle/gems/redis-rack-2.1.3/lib/rack/session/redis.rb:57:in `block (2 levels) in delete_session'
     # /usr/local/bundle/gems/redis-rack-2.1.3/lib/redis/rack/connection.rb:22:in `with'
     # /usr/local/bundle/gems/redis-rack-2.1.3/lib/rack/session/redis.rb:82:in `with'
     # /usr/local/bundle/gems/redis-rack-2.1.3/lib/rack/session/redis.rb:56:in `block in delete_session'
     # /usr/local/bundle/gems/redis-rack-2.1.3/lib/rack/session/redis.rb:70:in `with_lock'
     # /usr/local/bundle/gems/redis-rack-2.1.3/lib/rack/session/redis.rb:55:in `delete_session'
     # /usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:379:in `commit_session'
```

`commit_session` in rack calls `delete_session` which is overridden by rack-redis, however, a string is passed for the second argument when the method is called.
https://github.com/rack/rack/blob/2-2-stable/lib/rack/session/abstract/id.rb#L378

This change might be related.
https://github.com/redis-store/redis-rack/pull/50/files#diff-c50b22f679eb8e97b8f1dcda1da50f4bR57-R58

Any workaround?

**Comment by tubbo** [comment]
You might need to clear out sessions that are using the old format, or at least regenerate their IDs. The old session ID format is a String, but the newer format is an object with a `public_id` and `private_id` method.

**Comment by johnny-miyake** [comment]
The source of the problem was using an old version of **redis-actionpack**. I updated redis-actionpack from `5.0.2` to `5.2.0`, and the problem was solved. Since redis-actionpack 5.2.0 handles the new session ID format, it will not crash redis-rack.
