### ISSUE TITLE
Unclear how we should specify self-signed certificates for Redis TLS

### ISSUE THREAD

**Issue by soumyaray** [redis-store/redis-rack#65]
Greetings, I'm trying to setup a redis session store on Heroku, but want to specify the `ssl_params` option in connecting to Redis. I'm able to make a connection with a regular `redis://` connection but not with `rediss://`.

The following works with a plain Redis gem connection:

```ruby
redis = Redis.new(
  url: @config.REDIS_TLS_URL,
  ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
)
```

I wished to do something similar with `redis-rack`:

```ruby
use Rack::Session::Redis,
          expire_after: ONE_MONTH,
          redis_server: config.REDIS_TLS_URL,
          ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
```

However, the connection is failing and suggests that the ssl_params is not being found:

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)
	/Users/soumyaray/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/redis-4.2.5/lib/redis/connection/ruby.rb:260:in `connect_nonblock'

# rest of traceback removed
```

**Comment by soumyaray** [comment]
If it helps at all, it seems I need to essentially tell any open connections using OpenSSL to set `ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE`:
https://stackoverflow.com/questions/1113422/how-to-bypass-ssl-certificate-verification-in-open-uri

**Comment by tubbo** [comment]
if you want to pass params to the underlying Redis store, you need to pass them as `redis_server:`...

```ruby
use Rack::Session::Redis,
          expire_after: ONE_MONTH,
          redis_server: { url: config.REDIS_TLS_URL, ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE } }
```

**Comment by soumyaray** [comment]
Works brilliantly! Did I miss this somewhere in the documentation?  Otherwise I'm happy to issue a PR with such an example (maybe for the README) if folks wish.  This issue was prompted by Heroku Redis recently beginning to offer TLS connections, so I imagine more devs will want to know this.
