### ISSUE TITLE
[Feature Request] namespace (or key_prefix) option

### ISSUE THREAD

**Issue by mtgto** [redis-store/redis-rack#66]
I know  I can set key prefix by adding it after db number of redis url.

```ruby
Redis::Rack::Connection.new(redis_server: 'redis://localhost/0').store.set('baz', 'aaaa')
# => key is "baz"
Redis::Rack::Connection.new(redis_server: 'redis://localhost/0/foobar').store.set('baz', 'aaaa')
# => key is "foobar:baz"
```

But it is not a valid redis url in https://www.iana.org/assignments/uri-schemes/prov/redis .
(There is no leading string after db-number in url path)

I find why key prefix works by reading your source:

`Redis::Rack::Connection` gives only `redis_server` value option to `Redis::Store::Factory`.
https://github.com/redis-store/redis-rack/blob/v2.1.3/lib/redis/rack/connection.rb#L34-L36

`redis-store/redis-store` parses given url, use namespace as key prefix.
https://github.com/redis-store/redis-store/blob/v1.9.0/lib/redis/store/factory.rb#L72-L84

Is it a valid specification of `redis-store`, which keeping in future version?
Otherwise, can you give a namespace (or key prefix) option to carry it to redis-store?

**Comment by tubbo** [comment]
I think the intention is that you should be able to call

```ruby
Redis::Rack::Connection.new(redis_server: { url: 'redis://localhost/0', namespace: 'foobar' })
```

but if I'm reading [this code](https://github.com/redis-store/redis-store/blob/3acfa95f4eb6260c714fdb00a3d84be8eedc13b2/lib/redis/store/factory.rb#L72-L74) right, having any DB in the path might cause that to be overridden. So I think checking whether a `/` appears in the path should suffice in allowing the above configuration and still supporting URLs like

```ruby
Redis::Rack::Connection.new(redis_server: 'redis://localhost/0/foobar')
```

**Comment by tubbo** [comment]
**update:** The above code I posted does seem to work. Here's a quick test I wrote in `redis-store` to ensure that whatever you pass into `:redis_server` will be used as the arguments to `Redis::Store::Factory.create`. So you should be able to use the right namespace here while still providing an IANA-standard Redis URL:

```diff
diff --git a/test/redis/store/factory_test.rb b/test/redis/store/factory_test.rb
index cacd653..000645f 100644
--- a/test/redis/store/factory_test.rb
+++ b/test/redis/store/factory_test.rb
@@ -40,6 +40,12 @@
       it "uses specified namespace" do
         store = Redis::Store::Factory.create :namespace => "theplaylist"
         store.to_s.must_equal("Redis Client connected to 127.0.0.1:6379 against DB 0 with namespace theplaylist")
+
+        store = Redis::Store::Factory.create(
+          url: 'redis://127.0.0.1:6380/2',
+          namespace: 'foo'
+        )
+        store.to_s.must_equal("Redis Client connected to 127.0.0.1:6380 against DB 2 with namespace foo")
       end

       it "uses specified key_prefix as namespace" d
```

**Comment by mtgto** [comment]
@tubbo Thank you for your kindy explanation. 😃 

> I think the intention is that you should be able to call
Redis::Rack::Connection.new(redis_server: { url: 'redis://localhost/0', namespace: 'foobar' })

It code works!
I apologize for my lack of research of your source code 🙇 

----

As a matter of fact, I wanted to use redis-rack from redis-actionpack.
I use redis-server sharing some softwares, so I need to set key prefix to distinguish which keys is created by.
But I can't find the doc in redis-actionpack, redis-store and redis-rack how to define key prefix.
Thus I post this issue.

For now, my `config/initializers/session_store.rb` can define namespace (key prefix)!

```ruby
Rails.application.config.session_store :redis_store,
  servers: {
    redis_server: ENV['REDIS_SERVER_FOR_SESSION'],
    namespace: 'my_server', # dummy
  },
  expire_after: 1.day,
  key: '_my_server_session',
  threadsafe: true,
  secure: Rails.env.production?,
  httponly: true
```
