### ISSUE TITLE
Plans to release a 2.1.4?

### ISSUE THREAD

**Issue by pedrofurtado** [redis-store/redis-rack#68]
Hello, @tubbo ! 👋 

Thanks for you work on this gem 🍻 

Is there any plans to release a official 2.1.4 version? Because there are codes present in master, but not released together with 2.1.3 (code made by a PR from @krzysiek1507 🤝 ):

https://github.com/redis-store/redis-rack/compare/v2.1.3...master

Thanks a lot!

**Comment by tubbo** [comment]
Yup, just released v2.1.4. Sorry it took so long!
