### ISSUE TITLE
Release with support for Rack 3?

### ISSUE THREAD

**Issue by mmarinova-mm** [redis-store/redis-rack#74]
Greetings and thank you for providing this gem.
Snyk is reporting a vulnerability and I am hunting down gems in use in my project that have not released a version that supports Rack 3 yet. This seems to be one of them. Rails 7.1.0 also expects Rack > 3.0, it seems.

I see there was an update merged last year (https://github.com/redis-store/redis-rack/pull/73) but it is not yet released. Is there a timeline for the next release?

This is the exact mismatch error I receive:
```
  In Gemfile:
    rails (~> 7.1.0, >= 7.1) was resolved to 7.1.2, which depends on
      actionpack (= 7.1.2) was resolved to 7.1.2, which depends on
        rack-session (>= 1.0.1) was resolved to 2.0.0, which depends on
          rack (>= 3.0.0)

    redis-actionpack (>= 5.3.0) was resolved to 5.3.0, which depends on
      redis-rack (>= 2.1.0, < 3) was resolved to 2.1.4, which depends on
        rack (>= 2.0.8, < 3)
```

**Comment by radar** [comment]
This has just been released as redis-rack 3.0.
