### ISSUE TITLE
Rack::Session::Abstract::ID is deprecated

### ISSUE THREAD

**Issue by gawin** [redis-store/redis-rack#9]
The use of `Rack:Session::Abstract::ID` is deprecated and should be replaced with `Rack::Session::Abstract::Persisted`.

See:  https://github.com/rack/rack/commit/4224c028c71c4ccca7cdb3e5a10c51af797a4d4d

Would be great if this could be updated in a new release to ensure compatibility with newer versions of Rack.

**Comment by radar** [comment]
Hi @gawin! It appears you've submitted this as an _issue_ instead of a _pull request_. It's an easy mistake to make, so I will forgive you this time. Please correct this when you can :)

**Comment by gawin** [comment]
Hi @radar, when I was testing out `redis-rack` I found this issue. Since I'm not using `redis-rack` I unfortunately have no time available to deliver a patch accompanied with test cases and a nice pull request.

But I thought that it might be a good idea to give others a heads-up, before the new version of `rack` is released (which currently breaks `redis-rack`).

**Comment by radar** [comment]
Ok. I think we'll need to handle this by creating a new version of `redis-rack` when that new version of `rack` comes out. I'll leave this issue open.

**Comment by tubbo** [comment]
Going forward, `redis-rack` depends on and supports Rack v2.0.

**Comment by gawin** [comment]
👍
